version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - ./:/usr/src/patient_matching
    container_name: patient_matching_dev
    working_dir: /usr/src/patient_matching
    env_file:
      - .env
