# Publishes the patient_matching library to PyPI when a release is created
name: Publish Python Package (patient_matching)

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set release tag in VERSION
        working-directory: ./patient_matching
        run: echo "${{ github.event.release.tag_name }}" > VERSION

      - name: Install dependencies
        run: pip install -U pip setuptools wheel build

      - name: Build package
        working-directory: ./patient_matching
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: patient_matching/dist/

      - name: List files in dist
        run: ls -haltR patient_matching/dist

      - name: Persist wheels directory
        uses: actions/upload-artifact@v4
        with:
          name: wheel_${{ github.event.release.tag_name }}
          path: patient_matching/dist/*.whl
          if-no-files-found: error
